@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Mar 11 17:46:16 +0800 2024
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim SPU_tb_behav -key {Behavioral:sim_1:Functional:SPU_tb} -tclbatch SPU_tb.tcl -view D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/vivado_proj/Special_PU_simu/Special_PU_simu.srcs/sim_1/imports/Special_PU/simu/SPU_tb_behav.wcfg -log simulate.log"
call xsim  SPU_tb_behav -key {Behavioral:sim_1:Functional:SPU_tb} -tclbatch SPU_tb.tcl -view D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/vivado_proj/Special_PU_simu/Special_PU_simu.srcs/sim_1/imports/Special_PU/simu/SPU_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
