webtalk_init -webtalk_dir D:/RTL_projs/Special_PU_proj_mm/vivado_proj/Special_PU/Special_PU.sim/sim_1/behav/xsim/xsim.dir/SPU_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec  4 14:25:31 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b20c8adc-1809-4085-9408-261a59f38508" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "530e6c11471f4c9e94284f7509f8a135" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "18265" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-13700" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "73100 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "1.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "25128_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3971596497 -regid "" -xml D:/RTL_projs/Special_PU_proj_mm/vivado_proj/Special_PU/Special_PU.sim/sim_1/behav/xsim/xsim.dir/SPU_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/RTL_projs/Special_PU_proj_mm/vivado_proj/Special_PU/Special_PU.sim/sim_1/behav/xsim/xsim.dir/SPU_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/RTL_projs/Special_PU_proj_mm/vivado_proj/Special_PU/Special_PU.sim/sim_1/behav/xsim/xsim.dir/SPU_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
