# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.cache/wt} [current_project]
set_property parent.project_path {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/AdderTree.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/ConstantMultiplier_B.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/EU_B.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/LNU.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/LayerNorm.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/LayerNorm_Block.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/SoftMax.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/SoftMax_Block.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/ln_mean_var_reci.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/ln_xsum_mean.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/sm_max.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/sqrt_0.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/sources_1/new/Special_PU.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/constrs_1/imports/new/timing.xdc}}
set_property used_in_implementation false [get_files {{D:/OneDrive - HKUST Connect/ACCESS/Special_PU/Special_PU.srcs/constrs_1/imports/new/timing.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Special_PU -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Special_PU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Special_PU_utilization_synth.rpt -pb Special_PU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
