# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/vivado_proj/Special_PU_simu/Special_PU_simu.cache/wt} [current_project]
set_property parent.project_path {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/vivado_proj/Special_PU_simu/Special_PU_simu.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/vivado_proj/Special_PU_simu/Special_PU_simu.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {{D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/fpga_sdp_ram.sv}}
read_verilog -library xil_defaultlib {
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_divider_unsign.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_ln_block.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_ln_sqrt.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_ln_top.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_sm_addertree.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_sm_block.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_sm_expu_approx.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_sm_expu_approx_lut.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_sm_expu_pwl.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_sm_top.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/spu_sm_xmax.v}
  {D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/rtl/special_pu.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/vivado_proj/Special_PU/Special_PU.srcs/constrs_1/imports/new/timing.xdc}}
set_property used_in_implementation false [get_files {{D:/OneDrive - HKUST Connect/ACCESS/Special_PU_proj/vivado_proj/Special_PU/Special_PU.srcs/constrs_1/imports/new/timing.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top special_pu -part xc7vx485tffg1157-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef special_pu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file special_pu_utilization_synth.rpt -pb special_pu_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
